### ISSUE TITLE
Values not a member of a domain 

### ISSUE THREAD

**Issue by rockt** [wolfe-pack/naacl-demo#1]
In a moro notebook Scala cell with

``` scala
//the domain of parameters
@domain case class Theta(relations: IndexedSeq[Vect], pairs: IndexedSeq[Vect])

implicit val Thetas = Theta.Values(Seqs(Vectors(k), cols.size), Seqs(Vectors(k), rows.size))
```

I get

```
:50: error: value Values is not a member of object Theta
 Note: implicit value Thetas is not applicable here because it comes after the application point and it lacks an explicit result type
       implicit val Thetas = Theta.Values(Seqs(Vectors(k), cols.size), Seqs(Vectors(k), rows.size))
                                   ^
```

possibly caused by a missing dependency in the moro conf.

**Comment by riedelcastro** [comment]
Have you `publish-local`ed the latest wolfe version?

**Comment by rockt** [comment]
Yes I did that. Does it work for you? `@domain` isn't used anywhere in the statnlp book, right?

**Comment by riedelcastro** [comment]
Yes, you're right. But I think I used it in the new wolfe-docs. The trick was [here](https://github.com/wolfe-pack/moro/blob/master/app/controllers/ScalaIMainInterpreter.scala#L127-127), and I think @sameersingh wanted to generalize this at some point. Needs to be a property in the conf file...

**Comment by sameersingh** [comment]
For record, the original path is `.ivy2/cache/org.scalamacros/paradise_2.11.4/jars/paradise_2.11.4-2.1.0-M5.jar`, which `plugins` should be set to in `application.conf`.

**Comment by rockt** [comment]
I know that worked for luke, but I still can't get rid of the problem.
• I pulled the latest version of moro
• I added 
plugins ["/Users/rockt/.ivy2/cache/org.scalamacros/paradise_2.11.4/jars/paradise_2.11.4-2.1.0-M1.jar"]
to moro->compilers->scala in the application.conf 
• I made sure this jar file exists in my ivy cache
The MF notebook runs for Luke, does it work for you as well? Any ideas what could be wrong with my configuration?

**Comment by rockt** [comment]
I can't get it to work on my machine and I really don't know what's wrong. I have the same setup as Luke. Could we set up a moro online server where this works and I can edit the wolfe-docs from there?

**Comment by rockt** [comment]
@riedelcastro, is it working for you? For @sameersingh and me it's not :(

**Comment by riedelcastro** [comment]
Definitely worked yesterday **but** with the version where I added the plugin reference into the source code. I haven't tried the refactored version.

**Comment by riedelcastro** [comment]
Yes, also works with the refactored version. What's your classpath in moro.compilers.scala.classpath?

**Comment by riedelcastro** [comment]
I assume it contains a link to the wolfe-core class path, as in the moro build.sbt wolfe-core is commented out?

**Comment by sameersingh** [comment]
We're using this file: https://github.com/wolfe-pack/naacl-demo/blob/master/naacl-moro.conf

Are you using a different conf file?

**Comment by riedelcastro** [comment]
No I didn't know this existed---I am running moro out of a different repo right now.

**Comment by sameersingh** [comment]
Can you replace naacl-moro.conf with one that works?

**Comment by riedelcastro** [comment]
Here is my application.conf. It has local file references, so I just copy it here. Ignore the wolfe part.

```
moro {
    # document root
    docRoot = "/Users/riedel/projects/moro-notebooks/"
    views.editor.hideAfterCompile = false
    compilers {
        wolfe {
            classPath = [
                "/Users/riedel/projects/wolfe/wolfe-nlp/target/scala-2.11/classes",
                "/Users/riedel/projects/wolfe/wolfe-core/target/scala-2.11/classes"
            ]
        }
        scala {
            plugins = ["/Users/riedel/.ivy2/cache/org.scalamacros/paradise_2.11.4/jars/paradise_2.11.4-2.1.0-M5.jar"]
            aceTheme = "chaos"
            imports = [
                "org.sameersingh.htmlgen.D3jsConverter.Implicits._",
                "org.sameersingh.scalaplot.Implicits._",
                "org.sameersingh.htmlgen.Custom._",
                "org.sameersingh.htmlgen._",
                "ml.wolfe._",
                "ml.wolfe.Wolfe._",
                "ml.wolfe.macros.OptimizedOperators._",
                "ml.wolfe.D3Implicits._",
                "ml.wolfe.util.Multidimensional._",
                "ml.wolfe.nlp._",
                "ml.wolfe.ui._",
                "ml.wolfe.term.TermImplicits._",
                "ml.wolfe.term._",
                "ml.wolfe.term.Argmaxer._"
            ]
            classPath = [
                "../adi/target/scala-2.11/classes",
                "../stat-nlp-book/target/scala-2.11/classes",
                "/Users/riedel/projects/wolfe/wolfe-nlp/target/scala-2.11/classes",
                "/Users/riedel/projects/wolfe/wolfe-core/target/scala-2.11/classes"
            ]
            classesForJarPath = [
                "breeze.linalg.DenseVector",
                "breeze.macros.expand",
                "org.slf4j.Logger",
                "com.typesafe.scalalogging.slf4j.Logger",
                "scala.reflect.macros.Aliases",
                "ml.wolfe.term.Term",
                "ml.wolfe.util.Util",
                //"ml.wolfe.nlp.Token",
                "ml.wolfe.examples.DocClassifyExample"
                "ml.wolfe.ui.BratRenderer",
                //"ml.wolfe.macros.Library",
                "cc.factorie.model.Model",
                "org.sameersingh.htmlgen.Converter",
                "org.sameersingh.scalaplot.Implicits",
                "ml.wolfe.nlp.converters.SISTAProcessors",
                "edu.arizona.sista.processors.corenlp.CoreNLPProcessor",
                "com.typesafe.scalalogging.Logging",
                "com.typesafe.scalalogging.slf4j.LazyLogging"
            ]
            aggregate: true
        }

    }
}

```

**Comment by rockt** [comment]
Thanks, your configuration file works for me and Luke!
